### ISSUE TITLE
Add a source for the language declaration in the body tag

### ISSUE THREAD

**Issue by antoinentl** [FriendsOfEpub/eBookPerfChecklist#17]
Add a source for the point "Declare language on the `body` tag".

**Comment by JayPanoz** [comment]
OK source added in #16 but it basically says to attach it to the root element (html). 

Now since this issue seems to be about the `body` tag, I don't have any source but myself.

To sum up, it depends how the Reading System injects contents into its web view. iBooks, for instance, ignores `xml:lang` on `html` and this is why you must attach it to `body` as well. Else, hyphenation and TTS will be completely messed up.

**Comment by antoinentl** [comment]
Ok thanks for your feedback.

I will probably open an issue on [EPUB 3 Accessibility Guidelines](https://github.com/IDPF/a11y-guidelines/issues), it's more *coherent*!

I close this issue.

**Comment by antoinentl** [comment]
Done → [https://github.com/IDPF/a11y-guidelines/issues/6](https://github.com/IDPF/a11y-guidelines/issues/6)
